version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: das-dev-db
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    volumes:
      - das_dev_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - TZ=${TIME_ZONE}
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    container_name: das-dev-api
    command: python manage.py runserver 0.0.0.0:${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    volumes:
      - ./api_server:/usr/src/app/
    env_file: ./.env.dev
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: das-dev-front
    command: sh -c "HOST=${FRONT_HOST} PORT=${FRONT_PORT} NUXT_ENV_BACKEND_URL=${NUXT_ENV_BACKEND_URL} yarn dev"
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - api
    volumes:
      - ./front:/src
    env_file: ./.env.dev

volumes:
  das_dev_db:
